### ISSUE TITLE
add <a> tag arguments as defined by markdown v2.5.2

### ISSUE THREAD

**Issue by mikumikudice** [dillonkearns/elm-markdown#145]
currently there's no way to tag a link to redirect to a blank page (what could be done with `taget="_blank"` in pure html). the said version of markdown offers the `[link](url){:target="_blank"}` syntax. any chances of adding it?

I'm not familiar with elm enough for adding this myself (once it would require me to get used to elm _and_ the code base itself), so apologizes for this not being a pull request.

**Comment by dillonkearns** [comment]
`[link](url){:target="_blank"}` is a non-standard version of markdown, so that would definitely be out of scope for `elm-markdown`.

The philosophy of `elm-markdown` is a bit different than other markdown parsers in that it doesn't directly embed HTML, but instead you need to explicitly opt-in to handling specific HTML tags. But you can choose to handle `<a>` tags using this functionality. You can also customize the rendering for standard link tags to provide your own way to do that (for example, you could check if you have `?blank=true` at the end of a link and change that in the rendered markdown to show as target blank).

Feel free to ask for help in the markdown channel on the Elm slack if you have questions about any of that.
