### ISSUE TITLE
Refactor Markdown.Parser.Renderer type

### ISSUE THREAD

**Issue by matheus23** [dillonkearns/elm-markdown#15]
Hi!
Would it make sense to change the `Markdown.Parser.Renderer` type so that its `link` field changes the type like following?

```diff
    , link :
          { title : Maybe String
          , destination : String
          }
---       -> List view
---       -> Result String view
+++       -> Result String (List view -> view)
```

This issue came up, when I wanted to define a Markdown renderer that would contain model-dependent views. So I was trying to write a type `Markdown.Parser.Renderer (Model -> Html Msg)`.

This is possible today, by using a `renderer.link` defined like this:
```elm
\link children ->
    Ok <|
        \model -> Html.a [ Attr.href link.destination ] (List.map (\child -> child model) children)
```

But it was hoping I could define a function like `Markdown.Parser.Renderer view -> Markdown.Parser.Renderer (model -> view)`, so I could simply use the existing `link` renderer from `defaultHtmlRenderer`.

## A little further

To spin this proposal a little further, how about a type that doesn't contain `Result` at all?

```diff

type alias Renderer view =
    { heading : { level : Int, rawText : String, children : List view } -> view
    , raw : List view -> view
    , html : Markdown.Html.Renderer (List view -> view)
    , plain : String -> view
    , code : String -> view
    , bold : String -> view
    , italic : String -> view
--- , link : { title : Maybe String, destination : String } -> List view -> Result String view
--- , image : { src : String } -> String -> Result String view
+++ , link : { title : Maybe String, destination : String } -> List view -> view
+++ , image : { src : String } -> String -> view
    , list : List view -> view
    , codeBlock : { body : String, language : Maybe String } -> view
    , thematicBreak : view
    }
```

* `defaultHtmlRenderer` doesn't check for whether the links are dead anyways, so it might even be confusing that `defaultHtmlRenderer.link` returned a `Result` that is always `Ok` before. With this change, it would be obvious from the type that `defaultHtmlRenderer`doesn't validate links.
* It would be possible to write a function `checkLinks : String -> Renderer a -> Renderer (Result String a)` that would fail with `Err` and the given message, if a link is dead.
* The runtime would be simplified from `render : Renderer view -> List Block -> Result String (List view)` to `render : Renderer view -> List Block -> List view`.
* The `checkLinks` function would require the definition of a function `collectResults : List (Result e a) -> Result e (List a)`.
* It would be possible to write function `interactiveRenderer : Renderer a -> Renderer (model -> a)` that would be used like this:
   ```elm
   let
       renderer =
           interactiveRenderer defaultRenderer
   in
   { renderer | codeBlock = \code model -> viewMyCodeBlock code model }
   ```
   With a function `viewMyCodeBlock : { body : String, language : Maybe String } -> Model -> Html Msg`.

The render function at the `elm-pages` boundary would then be:
```elm
render renderer markdown =
    markdown
        |> Markdown.parse
        |> Result.mapError deadEndsToString
        |> Result.map (Markdown.render defaultHtmlRenderer)
```
Or, if one wants to check the links on render:

```elm
render renderer markdown =
    markdown
        |> Markdown.parse
        |> Result.mapError deadEndsToString
        |> Result.andThen (Markdown.render (Markdown.checkLinks "Dead Link!" defaultHtmlRenderer))
```
(The error message design is just preliminary)

I'd love to hear your thoughts! Keep in mind, this is just a suggestion, all of my issues can be worked around easily with today's API.

**Comment by dillonkearns** [comment]
Hello @matheus23! Thanks for sharing your thoughts. So I'm trying to follow, and I think I may need some clarification. Let me try to restate some things, and please let me know if I misunderstood anything!

* You're talking removing the `Result` types from the `Renderer` config record, and instead having it be part of an AST scanning step where you look at the blocks? So `Renderer`s will always succeed, and only 1) AST parsing and 2) checks on that AST (like dead link checks), could fail.
* You think one of the main advantages for doing this is that the type signature of the `defaultHtmlRenderer` becomes more clear

I wasn't quite following about the first section where you suggest the `link : ...` type changing to return `Result String (List view -> view)`. You mentioned that you can already depend on the model in your views. Is your concern that you need to wire it for each of these? Or something else? And I'm not sure how a change like that would address it, could you clarify?


> so I could simply use the existing link renderer from defaultHtmlRenderer

Is it worth making changes to the API for this rather than copy-pasting the `defaultHtmlRenderer`? Somehow my gut feeling is that changing the API design to optimize for the case of overriding bits and pieces of the `defaultHtmlRenderer` isn't the right direction. Some thoughts on why:

* I'd rather optimize for making the API really nice for building custom renderers from scratch, rather than optimize for making it really nice to override selective parts from the default html renderer
* I imagined the `defaultHtmlRenderer` as something that, if you use that, you would either style it with CSS, or just let the styles be the default styles because you need something simple. And if you need something customized, then you can copy-paste from the examples folder (something using `elm-ui`) or the code for the `defaultHtmlRenderer` and use that as a starting template and tweak as needed.
* What if you wanted to tweak the `defaultHtmlRenderer`, but you want to use a library like `elm-css` (which uses a different type for HTML values), or an accessible HTML package (which also uses a different type for HTML values). I think that pattern is pretty common.

Sorry for not understanding everything there! I'd love to talk it through more and explore. Feel free to message me on Slack as well, it may be easier to discuss it in real-time.

**Comment by matheus23** [comment]
> You're talking removing the Result types from the Renderer config record, and instead having it be part of an AST scanning step where you look at the blocks? So Renderers will always succeed, and only 1) AST parsing and 2) checks on that AST (like dead link checks), could fail.

Yes, exactly. In my example above, `Markdown.parse` would correspond to AST parsing, `checkLinks` would correspond with dead link checks and `Markdown.render` would correspond to rendering.

It would allow distinguishing something that *can* fail (`Renderer (Result String view)`) and something that cannot fail (`Renderer view`).

> You think one of the main advantages for doing this is that the type signature of the defaultHtmlRenderer becomes more clear

I do believe that is one of the advantages, but what I want even more is to be able to define **Combinators** for renderers:

```elm
checkLinks : Renderer view -> error -> Renderer (Result error view)

interactiveRenderer : Renderer view -> Renderer (model -> view)

-- I would consider something like bumpHeadings also as a combinator:
bumpHeadings : Int -> Renderer view -> Renderer view
```

I don't know what other combinators may be definable, but separating the error handling (`Result`) and from the Renderer enables new definition of combinators more easily.

> I'd rather optimize for making the API really nice for building custom renderers from scratch, rather than optimize for making it really nice to override selective parts from the default html renderer

I absolutely agree here. My statement about re-using the `defaultHtmlRenderer` for link rendering was not the best example. How about: You can define checking for dead links/making renderers interactive/other combinators within the library (with abstract parameters for `view`). This allows users to simply provide their own `Renderer view` that gets enhanced with all the available combinators.

I'm thinking about what would be the best way to illustrate these ideas. Maybe I can find time to mock up some API and create a PR. I understand that this might not be the right tradeoff between power and ease-of-use, so I understand that it might not be accepted. Is that a good idea?

I would love chatting, but I see we're on two very different time zones. At first I wanted to write this message to you on slack, but noticed that would mean I'm writing in the middle of the night (I'm sending this message several hours after that incident). And if that's the case, there is no upside to slack.

**Comment by matheus23** [comment]
I have started a prototypical implementation for this this morning.

[Here is the documentation](https://elm-doc-preview.netlify.com/Markdown-Renderer?repo=matheus23%2Felm-markdown&version=resultless-renderer)

[Here is the sourcecode](https://github.com/matheus23/elm-markdown/blob/resultless-renderer/src/Markdown/Renderer.elm)

**Comment by matheus23** [comment]
I think the 4.0.0 release from two weeks ago fixes this issue :)
