### ISSUE TITLE
README examples failing to compile on Ellie

### ISSUE THREAD

**Issue by sjansen** [dillonkearns/elm-markdown#22]
Appears to be a result of splitting `list` into `orderedList` and `unorderedList`.

Unfortunately I don't understand Elm well enough yet to offer a fix PR.

**Comment by dillonkearns** [comment]
Hello! I updated the examples in the README last week but I didn't publish any changes to the Elm package since then so they're not showing up there. I just published so it should be working now! Thank you!

Also, it's strange that the Ellie links broke... I don't think that's the intended behavior. If an Ellie version compiles, it should continue to compile forever. If new underlying packages are released, that shouldn't effect old Ellie links and break them. So anyway, surprising behavior that I think is not intended in Ellie.

Thanks for reporting the issue!
