### ISSUE TITLE
A line containing only spaces is invalid

### ISSUE THREAD

**Issue by kyasu1** [dillonkearns/elm-markdown#23]
Hi, Thank you for another great library !

I noticed that if my document contains a line with a space or spaces only, `Markdown.Parser.parse` shows the following errors.

```
Problem at row 1
Expecting ---
Problem at row 1
Expecting ***
Problem at row 1
Expecting ___
```

You can confirm this with your sample [app](https://ellie-app.com/7LDpp22bWKYa1) by clearing the text area then typing a space.

This is pretty annoying since it is hard to spot the lines with white spaces from a long document.

Is this an expected behavior ?

According to the GFM spec, at [section 2.1](https://github.github.com/gfm/#characters-and-lines), it says

> A line containing no characters, or a line containing only spaces (U+0020) or tabs (U+0009), is called a blank line.

**Comment by kyasu1** [comment]
Ahhh after writing this issue, I noticed this was mentioned in the following.

https://github.com/dillonkearns/elm-markdown/blob/master/test-results/failing/GFM/Blank%20lines.md

And I realized I could solve this by applying `String.trimRIght` to each line before parsing...

Thanks

**Comment by dillonkearns** [comment]
Hello @kyasu1 👋Thanks for the issue! Actually, if you don't mind, I would love to keep this issue open. Nice that you found a workaround, though, but it would certainly still be nice to get this fixed (especially because often markdown input could be coming from a CMS, for example).

I've found it really helpful to have issues for the next set of priorities to tackle, and this definitely seems like a good one 👍 I'll put a good first issue tag on it, too, would love contribution from someone in the community on this one.
